apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-keycloak
  labels:
    app: ms-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-keycloak
  template:
    metadata:
      name: ms-keycloak-pod
      labels:
        app: ms-keycloak
    spec:
      containers:
        - name: ms-keycloak-container
          image: quay.io/keycloak/keycloak:22.0.3
          command: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--db postgres" ]
          env:
            - name: KC_DB_URL
              value: jdbc:postgresql://ms-postgres-service:5432/keycloak
            - name: KC_DB_PASSWORD
              value: postgres
            - name: KC_DB_USERNAME
              value: postgres
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: HOSTNAME
              value: localhost
          ports:
            - containerPort: 8080
            - containerPort: 8787
          volumeMounts:
            - name: ms-keycloak-storage
              mountPath: /var/lib/keycloak/data
      volumes:
        - name: ms-keycloak-storage
          persistentVolumeClaim:
            claimName: ms-keycloak-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ms-keycloak-service
  labels:
    app: ms-keycloak
spec:
  selector:
    app: ms-keycloak
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8080
    - name: debug
      protocol: TCP
      port: 8787
      targetPort: 8787

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-keycloak-pvc
  labels:
    app: ms-keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi