kind: ConfigMap
apiVersion: v1
metadata:
  name: ms-admin
data:
  application.yml: |-
    spring:
      cloud:
        kubernetes:
          discovery:
            all-namespaces: true
            service-labels:
              spring-boot: true