CREATE SEQUENCE test_user_id_seq;

CREATE TABLE test_user
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL
);

ALTER SEQUENCE test_user_id_seq
    OWNED BY test_user.id;