server:
  port: 8080

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, health, info, metrics, loggers, routes, env, beans, configprops, mappings


logging:
  level:
    org:
      springframework:
        http:
          server:
            reactive: INFO
        cloud:
          gateway: INFO
