apiVersion: v1
kind: Service
metadata:
  name: ms-api-gateway
  labels:
    app: ms-api-gateway
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: ms-api-gateway
  type: LoadBalancer