version: '3.8'

services:
  ms-cms-service:
    image: ms-cms-service:latest
    ports:
      - "8100-8102:8100"
    deploy:
      replicas: 3
      mode: replicated
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ms-db:5432/cms
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ms-network

  ms-stock-service:
    image: ms-stock-service:latest
    ports:
      - "8091-8093:8082"
    deploy:
      replicas: 3
      mode: replicated
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ms-db:5432/stock
        - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ms-network

  ms-api-gateway:
    image: ms-api-gateway:latest
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      mode: replicated
    environment:
      - MS_STOCK_API=http://ms-stock-service:8100
      - MS_CMS_API=http://ms-cms-service:8081
      - SPRING_PROFILES_ACTIVE=docker
      - application-local.yml
    networks:
      - ms-network

networks:
    ms-network:
