version: '3'

services:
  ms-cms-service:
    image: cms-service:latest
    container_name: ms-cms-service
    ports:
      - "8081:8081"

  ms-stock-service:
    image: stock-service:latest
    container_name: ms-stock-service
    ports:
      - "8082:8082"

  ms-search-gateway:
    image: search-gateway:latest
    container_name: ms-search-gateway
    ports:
      - "8080:8080"