version: '3.8'

services:
  ms-cms-service:
    image: cms-service:latest
    ports:
      - "8100-8102:8081"
    deploy:
      replicas: 3
      mode: replicated
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ms-db:5432/cms
    networks:
      - ms-network

  ms-stock-service:
    image: stock-service:latest
    ports:
      - "8090-8092:8082"
    deploy:
      replicas: 3
      mode: replicated
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ms-db:5432/stock
    networks:
      - ms-network

  ms-search-gateway:
    image: search-gateway:latest
    ports:
      - "8080-8082:8080"
    deploy:
      replicas: 3
      mode: replicated
    environment:
      - MS_STOCK_API=http://ms-stock-service:8082
      - MS_CMS_API=http://ms-cms-service:8081
    networks:
      - ms-network

networks:
    ms-network:
