version: '3'

services:
  ms-cms-service:
    image: cms-service:latest
    container_name: ms-cms-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ms-db:5432/cms
    networks:
      - ms-network

  ms-stock-service:
    image: stock-service:latest
    container_name: ms-stock-service
    ports:
      - "8082:8082"
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ms-db:5432/stock
    networks:
      - ms-network

  ms-search-gateway:
    image: search-gateway:latest
    container_name: ms-search-gateway
    ports:
      - "8080:8080"
    environment:
      - MS_STOCK_API=http://ms-stock-service:8082
      - MS_CMS_API=http://ms-cms-service:8081
    networks:
      - ms-network

networks:
    ms-network:
