version: '3.8'
services:
  ms-db:
    image: postgres:15.1-alpine
    container_name: ms-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=stock,cms,keycloak
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/docker/volumes/microservice-search/postgres:/var/lib/postgresql/data
      - ./init_db_schema.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - ms-network

volumes:
  db:
    driver: local

networks:
  ms-network: