version: '3'

services:
  ms-zookeeper:
    image: wurstmeister/zookeeper
    container_name: ms-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ms-network

  ms-kafka:
    image: wurstmeister/kafka
    container_name: ms-kafka
    ports:
      - "9092:9092"
    depends_on:
      - ms-zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: ms-zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - ms-network


networks:
  ms-network: