version: '3.8'
services:
  mongodb:
    image: mongo:6.0.5
    restart: no
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/docker/volumes/microservice-search/mongodb_data:/data/db
volumes:
  mongodb_data:
    driver: local
