apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-postgres
  labels:
    app: ms-postgres
spec:
    replicas: 1
    selector:
        matchLabels:
          app: ms-postgres
    template:
        metadata:
          name: ms-postgres-pod
          labels:
            app: ms-postgres
        spec:
          containers:
          - name: ms-postgres-container
            image: postgres:15.1-alpine
            ports:
                - containerPort: 5432
            env:
                - name: POSTGRES_USER
                  value: postgres
                - name: POSTGRES_PASSWORD
                  value: postgres
                - name: POSTGRES_MULTIPLE_DATABASES
                  value: stock,cms,keycloak
            volumeMounts:
              - name: ms-postgres-storage
                mountPath: /var/lib/postgresql/data
              - name: ms-postgres-init
                mountPath: /docker-entrypoint-initdb.d/init.sh
                subPath: init_db_schema.sh
          volumes:
            - name: ms-postgres-init
              configMap:
                name: ms-postgres-init-db-script
            - name: ms-postgres-storage
              persistentVolumeClaim:
                claimName: ms-postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ms-postgres-service
  labels:
    app: ms-postgres
spec:
    selector:
        app: ms-postgres
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
    type: NodePort

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ms-postgres-storage
  labels:
    app: ms-postgres
spec:
    capacity:
        storage: 500Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
      path: /var/lib/docker/volumes/microservice-search/postgres

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-postgres-pvc
  labels:
    app: ms-postgres
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: 500Mi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-postgres-init-db-script
data:
  init_db_schema.sh: |
    #!/bin/bash
    set -e
    set -u
    function create_user_and_database() {
      local database=$1
      echo "  Creating user and database '$database'"
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
          CREATE USER $database;
          CREATE DATABASE $database;
          GRANT ALL PRIVILEGES ON DATABASE $database TO $database;
    EOSQL
    }
    if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
      echo "Multiple database creation requested: $POSTGRES_MULTIPLE_DATABASES"
      for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
        create_user_and_database $db
      done
      echo "Multiple databases created"
    fi





